module.exports = ({
name:"serverinfo",
aliases:['server','server-info'],
category:"Info",
explanation:"Get information about the server!",
bot:"Embed Links",
user:"None",
usage:"serverinfo",
example:"serverinfo",
explain:"Get the basic information about the server!",
code:`$reply[$messageid;{author:Information About The Server!:$servericon}{title:Below Is Your Requested Information!}{field:__**Basic Info**__:**Server Name#COLON#** $servername\n**ID#COLON#** $guildid\n**Owner#COLON#** <@$ownerid>\n**Creation Date#COLON#** $creationdate[$guildid;time] ago\n**Server Icon URLs#COLON#** [PNG]($replaceText[$servericon;webp;png]) | [WEBP]($replaceText[$servericon;png;webp]) | [JPEG]($replaceText[$replaceText[$servericon;webp;jpeg];png;jpeg]):no}{field:__**Channels Info**__:**Total Channel Count#COLON#** $channelcount\n**Text Channels#COLON#** $channelcount[text]\n**Voice Channels#COLON#** $channelcount[voice]\n**Stage Channels#COLON#** $channelcount[stage]:no}{field:__**Roles And Emojis**__:**Role Count#COLON#** $replacetext[$replacetext[$checkcondition[$rolecount==0];true;No roles have been made!];false;$rolecount]\n**Emoji Count#COLON#** $replacetext[$replacetext[$checkcondition[$emojicount==0];true;No emojis have been added!];false;$emojicount emojis]:no}{field:**__Members__**:**Total Members(Not Considering Bots)#COLON#** $memberscount[$guildid;all;no]\n**Bots#COLON#** $botcount\n#COLON#green_circle#COLON# **Online#COLON#** $memberscount[$guildid;online;no]     #COLON#black_circle#COLON# **Offline#COLON#** $memberscount[$guildid;offline;no]     #COLON#red_circle#COLON# **DND#COLON#** $memberscount[$guildid;dnd;no]     #COLON#yellow_circle#COLON# **Idle#COLON#** $memberscount[$guildid;idle;no]:no}{field:**__Other Info__**:**Verification Level#COLON#** $serverVerificationLevel\n**Content Filtering#COLON#** $serverContentFilter\n**Server Features#COLON#** $replaceText[$replaceText[$checkCondition[$serverFeatures==];true;None];false;$serverFeatures]:no}{field:**__Boost Related__**:**Boosts#COLON#** $replacetext[$replacetext[$checkcondition[$serverboostcount==0];true;No Boosts(0)];false;$serverboostcount]\n**Server Level#COLON#** $replacetext[$replacetext[$checkcondition[$serverboostlevel==0];true;No Level(0)];false;$serverboostcount]\n**Vanity URL#COLON#** $replacetext[$replacetext[$checkcondition[$vanityURL==];true;No Vanity URL];false;https://discord.gg/$vanityurl]:no}{thumbnail:$servericon}{footer:Requested by $usertag | Information of $servername:$authoravatar}{color:RANDOM};yes]
$servercooldown[10s;Woah woah wait, someone has just checked the server info!\n\nRemaining Time#COLON# **%time%**!]`})