module.exports = ({
name:"userinfo",
aliases:['ui','whois'],
category:"Info",
explanation:"Get information about any user in the server!",
bot:"Embed Links",
user:"None",
usage:"whois [user]",
example:"whois Stickman",
explain:"Gets the user information about the user **Stickman**!",
code:`$if[$message==]
$reply[$messageid;{author:Information about $usertag[$get[user]]:$useravatar[$get[user]]}{title:Here is the information about the requested user!}{field:__Basic User Information__:**ID#COLON#** $get[user]\n**Username#COLON#** $username[$get[user]]\n**Discriminator#COLON#** #$discriminator[$get[user]]\n**User Mention#COLON#** <@$get[user]>\n**Avatar URL#COLON#** [PNG]($replaceText[$servericon;webp;png]) | [WEBP]($replaceText[$servericon;png;webp]) | [JPEG]($replaceText[$replaceText[$servericon;webp;jpeg];png;jpeg]):no}{field:__Creation And Server Join Date__:**Time Passed Since Creation#COLON#** $creationdate[$get[user];time]\n**Time Passed Since Joining The Server#COLON#** $memberjoineddate[$get[user];time]:no}{field:__Roles__:**Is The User An Administrator#COLON#** $tolocaleuppercase[$hasperms[$get[user];admin]]\n**All Roles#COLON#** $replacetext[$replacetext[$checkcondition[$findnumbers[$charcount[$userroles[$get[user];mentions;, ]]]<=1850];true;$userroles[$get[user];mentions;, ]];false;Cannot Display Roles(There are a lot of them!)]\n**User Role Count#COLON#** $sub[$djsEval[message.guild.members.cache.get('$get[user]').roles.cache.size;yes];1]\n**Highest Role#COLON#** <@&$highestrole[$get[user]]>:no}{field:__Other Info__:**User Badges#COLON#** $replacetext[$replacetext[$checkcondition[$getuserbadges[$get[user]]==];true;None];false;$getuserbadges[$get[user]]]\n**State#COLON#** $replacetext[$replacetext[$replacetext[$replacetext[$status[$get[user]];dnd;:no_entry:];online;:green_circle:];idle;:yellow_circle:];offline;:black_circle:] $tolocaleuppercase[$status[$get[user]]]\n**Custom Status#COLON#** $getcustomstatus[$get[user];state]\n**Platform#COLON#** $replacetext[$replacetext[$replacetext[$platform[$get[user]];mobile;:mobile_phone:];web;:globe_with_meridians:];desktop;:desktop:] $tolocaleuppercase[$platform[$get[user]]]:no}{footer:Requested By $usertag:$authoravatar}{timestamp}{color:RANDOM}{thumbnail:$useravatar[$get[user]]};yes]
$let[user;$authorid]	
$elseif[$checkcontains[$checkcondition[$isnumber[$message]==true]$checkcondition[$mentioned[1]!=];true]==false]
$suppresserrors[]
$reply[$messageid;{author:Information about $usertag[$get[user]]:$useravatar[$get[user]]}{title:Here is the information about the requested user!}{field:__Basic User Information__:**ID#COLON#** $get[user]\n**Username#COLON#** $username[$get[user]]\n**Discriminator#COLON#** #$discriminator[$get[user]]\n**User Mention#COLON#** <@$get[user]>\n**Avatar URL#COLON#** [PNG]($replaceText[$servericon;webp;png]) | [WEBP]($replaceText[$servericon;png;webp]) | [JPEG]($replaceText[$replaceText[$servericon;webp;jpeg];png;jpeg]):no}{field:__Creation And Server Join Date__:**Time Passed Since Creation#COLON#** $creationdate[$get[user];time]\n**Time Passed Since Joining The Server#COLON#** $memberjoineddate[$get[user];time]:no}{field:__Roles__:**Is The User An Administrator#COLON#** $tolocaleuppercase[$hasperms[$get[user];admin]]\n**All Roles#COLON#** $replacetext[$replacetext[$checkcondition[$findnumbers[$charcount[$userroles[$get[user];mentions;, ]]]<=1850];true;$userroles[$get[user];mentions;, ]];false;Cannot Display Roles(There are a lot of them!)]\n**User Role Count#COLON#** $sub[$djsEval[message.guild.members.cache.get('$get[user]').roles.cache.size;yes];1]\n**Highest Role#COLON#** <@&$highestrole[$get[user]]>:no}{field:__Other Info__:**User Badges#COLON#** $replacetext[$replacetext[$checkcondition[$getuserbadges[$get[user]]==];true;None];false;$getuserbadges[$get[user]]]\n**State#COLON#** $replacetext[$replacetext[$replacetext[$replacetext[$status[$get[user]];dnd;:no_entry:];online;:green_circle:];idle;:yellow_circle:];offline;:black_circle:] $tolocaleuppercase[$status[$get[user]]]\n**Custom Status#COLON#** $getcustomstatus[$get[user];state]\n**Platform#COLON#** $replacetext[$replacetext[$replacetext[$platform[$get[user]];mobile;:mobile_phone:];web;:globe_with_meridians:];desktop;:desktop:] $tolocaleuppercase[$platform[$get[user]]]:no}{footer:Requested By $usertag:$authoravatar}{timestamp}{color:RANDOM}{thumbnail:$useravatar[$get[user]]};yes]
$suppresserrors[]
$let[user;$findMember[$djseval[message.guild.members.fetch().then(a => a.find(x =>x.user.username.toLowerCase().includes('$message'.toLowerCase())).user.id);yes];yes]]
$suppresserrors[]
$endelseif
$else
$reply[$messageid;{author:Information about $usertag[$get[user]]:$useravatar[$get[user]]}{title:Here is the information about the requested user!}{field:__Basic User Information__:**ID#COLON#** $get[user]\n**Username#COLON#** $username[$get[user]]\n**Discriminator#COLON#** #$discriminator[$get[user]]\n**User Mention#COLON#** <@$get[user]>\n**Avatar URL#COLON#** [PNG]($replaceText[$servericon;webp;png]) | [WEBP]($replaceText[$servericon;png;webp]) | [JPEG]($replaceText[$replaceText[$servericon;webp;jpeg];png;jpeg]):no}{field:__Creation And Server Join Date__:**Time Passed Since Creation#COLON#** $creationdate[$get[user];time]\n**Time Passed Since Joining The Server#COLON#** $memberjoineddate[$get[user];time]:no}{field:__Roles__:**Is The User An Administrator#COLON#** $tolocaleuppercase[$hasperms[$get[user];admin]]\n**All Roles#COLON#** $replacetext[$replacetext[$checkcondition[$findnumbers[$charcount[$userroles[$get[user];mentions;, ]]]<=1850];true;$userroles[$get[user];mentions;, ]];false;Cannot Display Roles(There are a lot of them!)]\n**User Role Count#COLON#** $sub[$djsEval[message.guild.members.cache.get('$get[user]').roles.cache.size;yes];1]\n**Highest Role#COLON#** <@&$highestrole[$get[user]]>:no}{field:__Other Info__:**User Badges#COLON#** $replacetext[$replacetext[$checkcondition[$getuserbadges[$get[user]]==];true;None];false;$getuserbadges[$get[user]]]\n**State#COLON#** $replacetext[$replacetext[$replacetext[$replacetext[$status[$get[user]];dnd;:no_entry:];online;:green_circle:];idle;:yellow_circle:];offline;:black_circle:] $tolocaleuppercase[$status[$get[user]]]\n**Custom Status#COLON#** $getcustomstatus[$get[user];state]\n**Platform#COLON#** $replacetext[$replacetext[$replacetext[$platform[$get[user]];mobile;:mobile_phone:];web;:globe_with_meridians:];desktop;:desktop:] $tolocaleuppercase[$platform[$get[user]]]:no}{footer:Requested By $usertag:$authoravatar}{timestamp}{color:RANDOM}{thumbnail:$useravatar[$get[user]]};yes]
$let[user;$findmember[$message;yes]]
$endif`})